stages:
  prepare_data:
    cmd: python experiment/prepare_data.py
    deps:
      - experiment/prepare_data.py
    outs:
      - assets_exp/data/df_raw.csv
      - assets_exp/data/splits/train/raw.csv
      - assets_exp/data/splits/val/raw.csv
      - assets_exp/data/splits/test/raw.csv

  text_normalization: # text_normalization
    cmd: python experiment/text_normalization.py
    deps:
      - experiment/text_normalization.py
      - assets_exp/data/splits/train/raw.csv
      - assets_exp/data/splits/val/raw.csv
      - assets_exp/data/splits/test/raw.csv
    outs:
      - assets_exp/data/splits/train/preprocessed.csv
      - assets_exp/data/splits/val/preprocessed.csv
      - assets_exp/data/splits/test/preprocessed.csv

  feat_extract_deep:
    cmd: python experiment/supervised_deep_models/feat_extract_deep.py
    deps:
      - experiment/supervised_deep_models/feat_extract_deep.py
      - assets_exp/data/splits/train/preprocessed.csv
      - assets_exp/data/splits/val/preprocessed.csv
    outs:
      - assets_exp/deep_assets/word2vec.model
      - assets_exp/data/splits/train/padded.csv
      - assets_exp/data/splits/val/padded.csv

  tuning_models:
    cmd: python experiment/supervised_deep_models/tuning_models.py
    deps:
      - experiment/supervised_deep_models/tuning_models.py
      - assets_exp/data/splits/train/padded.csv
      - assets_exp/data/splits/val/padded.csv
      - assets_exp/deep_assets/word2vec.model
      - assets_exp/deep_assets/tokenizer.json
    outs:
      - assets_exp/deep_assets/lstm_model
      - assets_exp/deep_assets/bilstm_model

  evaluate_models:
    cmd: python experiment/supervised_deep_models/evaluate_models.py
    deps:
      - experiment/supervised_deep_models/evaluate_models.py
      - assets_exp/data/splits/test/preprocessed.csv
      - assets_exp/deep_assets/word2vec.model
      - assets_exp/deep_assets/tokenizer.json
      - assets_exp/deep_assets/lstm_model
      - assets_exp/deep_assets/bilstm_model
    outs:
      - assets_exp/deep_assets/deep_results.csv # or graph similar to the one in the paper

#  apply_model:
#    cmd: python experiment/supervised_deep_models/apply_model.py
#    deps:
#      - assets_exp/data/splits/test/raw.csv
#      - assets_exp/deep_assets/word2vec.model
#      - assets_exp/deep_assets/tokenizer.json
#      - assets_exp/deep_assets/lstm_model
#    outs:
#      - assets_exp/deep_assets/predictions.csv